### ISSUE TITLE
You have exceeded your quota

### ISSUE THREAD

**Issue by chrisugit** [noitcudni/google-webmaster-tools-bulk-url-removal#15] opened 2018-05-16 23:08 UTC
Your script is working well, but after a couple of submitted URLs (the amount differs) a blank page appears with a message like "You have exceeded your quota". Clicking the Back-Button (also several times) keeps the script working again.

**Comment by noitcudni** [comment] 2018-05-17 00:20
A couple of people raised this issue before.  Roughly, how many urls are you trying to remove?  I guess I could mark the ones that have been removed and detect "You have exceeded your quota" and stop the script. Finally, provide a way to restart.

First step, I'd like to know roughly what the limit is. I will try to reproduce the problem on my end.

**Comment by chrisugit** [comment] 2018-05-17 09:56
I tryed to submit 380 URLs at once. Actually, after ending the script, 324 were taken, means 56 were removed.

I don't know exactly which URLs were not taken, but lets say the first 70 worked without a problem. Then, the first message "You have exceeded your quota" appeared. The more URLs were processed, more often appeared this message. Perhaps a point to look at is that the first URLs are ending with "=". All the late URLs submitted are ending with "/". Strange, but perhaps this is related to the problem?

**Comment by chrisribe** [comment] 2018-06-07 21:02
Got the same thing, probably google set a limit on the number of urls per hour / day you can submit.

**Comment by noitcudni** [comment] 2018-06-09 19:47
Can someone copy and paste the url that shows "You have exceeded your quota"?

**Comment by noitcudni** [comment] 2018-06-10 02:27
Added a new content_script against what I think the "exceed quota" url is.
Once the page with "you have exceeded your quota!" shows up, the extension will wait for 3 minutes. The extension also adds a countdown timer to that page, so that the user knows when it's going to continue. 

The goal is that you don't need to click on the back button manually.

Please try out this branch
https://github.com/noitcudni/google-webmaster-tools-bulk-url-removal/tree/exceed-quota
and let me know if it works for you guys.

**Comment by dailybits** [comment] 2018-06-15 08:43
The script is now working on a list with 900url's without any problems. Great work!

**Comment by noitcudni** [comment] 2018-06-17 21:56
@dailybits  Thanks for trying it out.

**Comment by dmsims** [comment] 2018-07-04 08:06
I received this message a few times

Files contained 100 entries

Chrome 67.0.3396.99

When the quota message apperaed there was no countdown timer

These were the URL's for the quota message (actual site removed)

https://www.google.com/webmasters/tools/removals-submit-ac?hl=en&siteUrl=https://somesite.com/

https://www.google.com/webmasters/tools/url-removal?hl=en&siteUrl=https://somesite.com/&mesd=AB9YKzLTZH2agfSWpweMwQdXPgrPuDOlYWLicJQf_n3f6rReWm3TZbU5mAE6fBAR_rMBjFTLhFIKyvB8nn48iSY-nMhTqUdrXGL46AGJ183FKjA8Ms2t24Y

https://www.google.com/webmasters/tools/url-removal?hl=en&siteUrl=https://somesite.com/&mesd=AB9YKzIpX0tSfk8pKZaW8WpJJTNwvSsnivYuUrNXraxtfWQ74PIl8Kir5T3mdkepqHUO2s-V8h1naai0vDnqbphK2SZ4GZ8BLn2EmPRjQIkEHusO850SleP4aiK1qIbvVxcMbyIeHyGpiJA_eVaip00guRoK7gICxpKX1i1KLHR3qObi5-TOZ8PmbXNgt8Llc_tPEUYRhmzq

https://www.google.com/webmasters/tools/removals-submit-ac?hl=en&siteUrl=https://somesite.com/

**Comment by noitcudni** [comment] 2018-07-04 17:06
Thanks for letting me know. If it's not too much trouble, can you take a couple screenshots? I'll try to take a look at it this weekend. I wonder if google changed something on their end.

**Comment by noitcudni** [comment] 2018-07-04 17:08
@dmsims By the way, did you install the extension from chrome webstore or cloned it from the master branch?

**Comment by dmsims** [comment] 2018-07-04 18:00
I cloned it from the master today

Interestingly later I did get the timer (but only once) and not on subseqeunt runs

Pressing the back button always seem to resume the script

![image](https://user-images.githubusercontent.com/4712953/42290359-b0d0fb20-7fbc-11e8-86cb-86e663392a3f.png)

**Comment by jammersdublin** [comment] 2018-07-10 15:26
The last time I used this extension, I ran into the quota issue quite a few times, I've tried today with 250 links (so far) and haven't hit the limit at all. Glad this extension is getting some active development, it's a godsend for getting rid of stock content from wordpress themes, as well as amp pages once you disable it

**Comment by shendison** [comment] 2018-11-10 19:54
Just used it again,  and got "You have exceeded your quota limit!"  after just 35 - I hit the back button and it started right up again  -  then another 50 or so before another warning  - hit back again and finished the 128 total...  looks like there's no set number for the quota.

**Comment by jammersdublin** [comment] 2018-11-12 17:52
I wonder if it’s to do with the amount of queries within a certain timeframe that triggers it. I can’t code, but I’ve seen situations before where if there’s too many ‘rapid fire’ queries it’ll trigger a lock. I know with a plug-in I use for google search that shows all the page results , if you do too many quickly it’ll ask for a captcha saying it’s unusual traffic. 

And the ‘quota’ message might be a little off the mark, I haven’t ever had a problem getting hundreds of pages done in a short enough period of time, just when it was cycling through a lot or after the other and after a cooldown of a couple of minutes it always let me continue

**Comment by noitcudni** [comment] 2018-11-13 02:33
@shendison I've been trying to get the "You have exceeded your quota limit!" page. So far, I haven't been able to. What's the url that shows "You have exceeded your quota limit!"?

**Comment by noitcudni** [comment] 2018-11-13 03:19
![screen shot 2018-11-12 at 7 15 14 pm](https://user-images.githubusercontent.com/78951/48388754-5d132080-e6af-11e8-9bf6-56f8557732a0.png)

I'm seeing this now. After I submitted a bunch of URLs. Did anyone encounter this before?

**Comment by noitcudni** [comment] 2018-11-13 03:29
I totally missed this one. According to @dmsims (thanks btw), the url for "You have exceeded your quota limit!" was https://www.google.com/webmasters/tools/removals-submit-ac...

I'm catching only `removals-create-ac*`. I suppose I'll need to watch out for both.

**Comment by jammersdublin** [comment] 2018-11-15 15:18
@noitcudni yes this is the error that crops up occasionally. the submission limit seems to be based on time, it's not like i do 100 links, and then have to wait 24 hours for the next process, it's popped up in a scenario where I was removing say 250 pages (a wordpress site that had stock pages/tags/categories indexed), then it might come up randomly after x URLs, but after a short cooldown (less than 10 minutes), I could continue, and it might show up again after another x which makes me think it's seeing lots of rapid fire requests in short succession, and that's causing the temporary cooldown period, not the # of URLs in total that you're doing. I've done up to 450 urls on the same day.

I'd say throttling it a little, ie x seconds between each request might prevent it, and having it running on a second screen, taking a little longer, but not hitting the limit isn't a major issue. It's still wayyyyyyyyyy quicker than doing it all manually, and this is why I **love** this tool you made

**Comment by raramuridesign** [comment] 2018-11-21 15:17
Hi All, does this work without the timeout. 
We need to submit more than 170.000 links - would like to know if this is possible, otherwise, we might be doing this for several weeks...

**Comment by noitcudni** [comment] 2018-11-26 05:08
With 170k links, you will mostly run into the quota limit. As @jammersdublin suggested, you can give it a go, come back an hour or so and hit the back button to resume.

**Comment by Braindead81** [comment] 2019-03-26 14:06
Hello,
I have the same problem.
I tried to submit 6000 urls but the error appears after 580 urls.
But the problem is each time i try to load the Google removal page the plugin is running.

Could you not just add a way to reset it and after one hour we can try with a new file of urls?

Thanks,
François

**Comment by noitcudni** [comment] 2019-03-26 17:33
For now, I'd suggest splitting your 6000 urls into smaller chunks and do one chunk at a time.
To get around the restart issue, you can disable to plugin and restart your chrome browser. The `next` "victim" is stored in memory, so it should go away upon restart.

**Comment by Pls** [comment] 2019-07-16 15:19
@noitcudni Is your extension still working properly? I seem to not see Timer when Quota Exceeded Limit error is displayed. Love your extension, but just want it to work regarding this quota error.

Actually, for me the script continues to execute Removal even when Exceeded Quota error is displayed. So, maby there should be modifications to prevent from this? I have read that delay between 1000 URL removals should be at least 1 hour. Is this correct assumption?

If that's correct, then would be nice to automate it - bulk remove 1000 URLs and then wait 1 hour 2 minutes, then continue. What do you think?

**Comment by noitcudni** [comment] 2019-07-16 17:12
It's entirely possible that Google has made some changes on their end that
causes the extension not pausing when the quota has been reached.

Hmm..maybe a better way of handling it is to record the ones that have
gotten removed successfully. Also, adding a pause button to the extension.
So, basically, my goal is to give the end users more control over when to
pause and restart. Do you think that would solve this issue?

**Comment by Pls** [comment] 2019-07-16 18:10
Yep, that is very good plan I believe! Let me know if you need testing, I am available for that.

Also, what could be nice is a count up timer, for user to see when the last removal request was executed. This way we could see when the next retry is possible (which would prevent from quota limit error). Like one hour from last attempt. Makes sense, what do you think?

**Comment by noitcudni** [comment] 2019-08-24 04:25
Just committed my changes. In fact, I wrote the whole thing in clojurescript. Can't stand javascript any longer. 

Now should you counter any errors, the extension should pause. It will then show you a continue button. Wait however long you want and click on the continue button to continue.

**Closed as completed** 2020-02-28 04:57 UTC

**Comment by kelvinn07** [comment] 2020-11-23 03:50
Hi, @noitcudni 

I bought your Google Chrome extension and I am currently experiencing this issue as well.

Please refer to attached.

![quota error](https://user-images.githubusercontent.com/74889063/99927858-d1dec200-2d81-11eb-9b86-8afae417a48a.png)

I used this without issues for the 1st batch of URLs and experienced this while uploading the 2nd batch. (Both batches are about 1000 URLs)

Kindly advise as I have more URLs to submit for removal request.

Thank you.

**Comment by noitcudni** [comment] 2020-11-23 15:48
Google imposes the Daily quota, not the extension. You'll just have to wait a day or so and try again

**Comment by kelvinn07** [comment] 2020-11-24 02:32
Hi @noitcudni 

Thanks for getting back.

Noted on that. Can I also check with you something regarding the URLs for “indexed, not submitted in sitemap”

I have about 6000 plus URLs that belongs to that category which I intend to request for removal. 

But when I try to export, my export only contains a list of 1000 URLs. 

Do you have any idea why? Please kindly advise.

Thank you.

**Comment by noitcudni** [comment] 2020-11-24 03:25
Other users did bring that to my attention in the past. Unfortunately,
through google search console's UI, you can only export 1000 URLs. If I
remember correctly, in the UI, it only shows you the first 1000.

Maybe you can remove the first 1000 and see if the table shows the next
1000. Repeat the process until you exhaust all 6000.

Lih
